### 1. 张量(Tensor)是什么？

#### 1.1 数学概念
张量在数学概念中就是一个多维数组，它是标量，向量，矩阵的高纬拓展，比如彩色图像有三个通道，就是平面图像的在第三个维度的扩展
#### 1.2 在torch中的概念
variable是0.4版本之前的一种重要的数据结构，虽然在新版本中已经封装到Tensor中，但是还是重要的基础。
它有如下五个的属性：
- data: 被包装的Tensor
- grad: data的梯度
- grad_fn: 创建Tensor的Function, 是自动求到的关键
- requires_grad: 指示是否需要梯度
- is_leaf: 指示是否是叶子节点(张量)

Pytorch在0.4.0版本以后, Varibale并入Tensor, 并新增了三个属性:
- dtype: 张量的数据结构，如 torch.FloatTensor, torch.cuda.FloatTensor, 卷积层的参数和图像的数值常用torch.float(32-bit floating point), 分类的标签值常用torch.long(64-int integer)
- shape: 张量的形状, 如(64, 3, 224, 224)
- device: 张量所在设备, GPU/CPU, 是加速的关键 

#### 1.3 Tensor的创建
总结: 
- 直接创建: <font color=blue>常见:torch.tensor;torch.from_numpy, 需要注意的是tensor与dnarray共享内存</font>
- 依据数据创建: <font color=blue>比如全零, 全一, 自定义, 等差数列, 均分数列, 对数均分数列, 单位矩阵</font>
- 依据概率创建: <font color=blue>正态分布, 标准正态分布, 整数均匀分布, 以及波努力分布</font>

##### 1.直接创建   
###### 1.1 - torch.tensor()   
功能: 从data创建tensor   
- data: 数据，可以是list，numpy
- dtype: 数据类型，默认与data的一致
- device: 所在设备，cuda／cpu
- requires_grad: 是否需要梯度
- pin_memory: 是否存于锁页内存


In [39]:
import numpy as np
import torch

arr = np.ones((3,3))
print("The datatype of ndarray: ", arr.dtype)

The datatype of ndarray:  float64


In [43]:
# 观察到tensor的类型和darray的数据类型一致
t = torch.tensor(arr)
print(t)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


*** 
###### 1.2 - torch.from_numpy(ndarray)   
功能: 从numpy创建tensor

<font color=blue>注意事项</font>: 从torch.from_numpy创建的tensor与原ndarray<font color=blue>共享内存</font>，当修改其中一个的数据，另外一个也将会被改动


In [11]:
arr = np.array([[1,2,3], [4,5,6]])
t = torch.from_numpy(arr)
print("numpy array: \n", arr)
print("tensor: \n", t)

numpy array: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
# 观察到单独修改其中一个都会影响到另一个，它们是共享内存的
print("修改arr后:")
arr[0,0] = 0
print("numpy array: \n", arr)
print("tensor: \n", t)

print("\n 修改tensor后:")
t[0,0] = -1
print("numpy array: \n", arr)
print("tensor: \n", t)

修改arr后:
numpy array: 
 [[0 2 3]
 [4 5 6]]
tensor: 
 tensor([[0, 2, 3],
        [4, 5, 6]])

 修改tensor后:
numpy array: 
 [[-1  2  3]
 [ 4  5  6]]
tensor: 
 tensor([[-1,  2,  3],
        [ 4,  5,  6]])


---
##### 2.依据数值创建   
###### 2.1  torch.zeros()   
功能: 依size创建全0张量
- size: 张量的形状, 如(3,3), (3,244,244) 
- out: 输出的张量
- layout: 内存中布局形式, 有strided, sparse_coo等, 当是稀疏张量时可以设置, 提高内存效率
- device: 所在设备, gpu/cpu
- requires_grad: 是否需要梯度

```python
torch.zeros(*size,
            out=None
            dtype=None,
            layout=torch.strided,
            device=None,
            requires_grad=False)
```



In [15]:
out_t = torch.tensor([1])
t = torch.zeros((3,3), out=out_t)

# t 和 out_t 的内存地址一样
print(t, '\n', out_t)
print(id(t), id(out_t), id(t)==id(out_t))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
4914215600 4914215600 True


*** 
###### 2.2 torch.zeros_like()   
功能: 依input形状创建全0张量
- input: 创建与input同形状的全0张量
- dtype: 数据结构
- layout: 内存中的布局结构


```python
torch.zeros_like(input,
                 dtype=None,
                 layout=None,
                 device=None,
                 requires_grad=False)
```

----


###### 2.3/2.4 torch.ones()/torch.ones_like()   
全一张量的创建和之前的全零基本完全一致
```python
torch.ones(*size,
           out=None
           dtype=None,
           layout=torch.strided,
           device=None,
           requires_grad=False)

torch.ones_like(input,
                dtype=None,
                layout=None,
                device=None,
                requires_grad=False)
```
------

###### 2.5/2.6 torch.full()/torch.full_like()   
功能: 依input形状创建全0张量   
- size: 张量的形状, 如(3,3)
- fill_value: 张量的值
```python
torch.full(*size,
           fill_value,
           out=None,
           dtype=None,
           layout=torch.strided,
           device=None,
           requires_grad=False)
```

In [16]:
t = torch.full((3,3), 10)
print(t)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])


----
###### 2.7 torch.arange()   
功能: 创建等差的1维张量    
注意事项: 数值区间为[start, end)
- start: 数列起始值
- end: 数列“结束值”
- step: 数列公差， 默认为1
```python
torch.arange(start=0,
             end,
             step=1,
             out=None,
             dtype=None,
             layout=torch.strided,
             device=None,
             requires_grad=False)
```

In [17]:
# 创建一个偶数数列，注意是左闭右开
t = torch.arange(0,10,2)
print(t)

tensor([0, 2, 4, 6, 8])


--- 
###### 2.8 torch.linspace()    
功能: 创建均分的1维张量    
注意事项: 数值区间为[start, end]
- start: 数列起始值
- end: 数列“结束值”
- step: 数列长度
```python
torch.linspace(start=0,
               end,
               step=100,
               out=None,
               dtype=None,
               layout=torch.strided,
               device=None,
               requires_grad=False)
```
---
###### 2.9 torch.logspace()    
功能: 创建均分的1维张量    
注意事项: 长度为steps，底为base
- start: 数列起始值
- end: 数列“结束值”
- step: 数列长度
- base: 对数函数的底，默认为10

In [18]:
# 步长 = (end-start)/(step-1)
t = torch.linspace(2,10,6)
print(t)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


###### 2.10 torch.eye()   
功能: 创建单位对角矩阵(2维张量)
注意事项: 默认方阵
- n: 矩阵行数
- m: 矩阵列数

---
##### 3.依据概率分布创建张量    
###### 3.1 torch.normal()    
功能: 生成正态分布   
- mean: 均值
- std: 标准差   
四种模式:    
mean为标量, std为标量   
mean为标量, std为张量   
mean为张量, std为标量   
mean为张量, std为张量

In [22]:
# mean: 张量, std: 张量
mean = torch.arange(1, 5, dtype=torch.float)
std = torch.arange(1, 5, dtype=torch.float)
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}\nout_tensor:{}".format(mean, std, t_normal))
# out_tensor:tensor([1.0040, 2.0221, 3.3154, 4.5225]) 分别是四个不同的正态分布得到的

mean:tensor([1., 2., 3., 4.])
std:tensor([1., 2., 3., 4.])
out_tensor:tensor([1.0040, 2.0221, 3.3154, 4.5225])


In [28]:
# mean: 张量, std: 张量
t_normal = torch.normal(0., 1., size=(4,))
print(t_normal)
# out_tensor:tensor([1.0040, 2.0221, 3.3154, 4.5225]) 

tensor([ 0.2219, -1.1354,  0.2321,  0.5560])


In [29]:
# mean: 张量, std: 张量
mean = torch.arange(1, 5, dtype=torch.float)
std = 1
t_normal = torch.normal(mean, std)
print("mean:{}\nstd:{}\nout_tensor:{}".format(mean, std, t_normal))
# 

mean:tensor([1., 2., 3., 4.])
std:1
out_tensor:tensor([0.4883, 2.2987, 2.9339, 3.8829])


---
###### 3.2/3.3 torch.randn() / torch.rand_like()    
功能: 生成标准正态分布    
- size: 张量的形状
--- 
###### 3.4 torch.rand()   
###### 3.5 torch.rand_like()   
功能: 在区间[0,1)上，生成均匀分布    
```python
torch.rand(*size,
           out=None,
           dtype=None,
           layout=torch.strided,
           device=None,
           requires_grad=False)
```
---
###### 3.6 torch.randint()    
###### 3.7 torch.randint_like()    
功能: 区间[low, high)生成整数均匀分布
- size: 张量的形状
```python
torch.randint(low=0,
              high,
              size,
              out=None
              layout=torch.strided,
              device=None,
              requires_grad=False)
```
---
###### 3.8 torch.randprem()   
功能: 生成丛0到n-1的随机排列，<font color=blue>最常见用来生产一个乱序的索引</font> 
- n: 张量的长度   
```python
torch.randprem(n,
               out=None
               layout=torch.strided,
               device=None,
               requires_grad=False)
```
---
###### 3.9 torch.bernoulli()   
功能: 以input为概率，生成波努力分布(0-1分布，两点分布)
- n: 张量的长度   
```python
torch.bernoulli(input,
                *,
                generator=None,
                out=None)
```

In [45]:
pro = torch.tensor([0.9, 0.1, 0.6, 0.7])
torch.bernoulli(pro)

tensor([1., 0., 0., 1.])